server:
  port: 8040
spring:
  application:
    name: core-service
  data:
    mongodb:
      username: david
      password: david
      host: localhost
      port: 27017
      database: payments
      authentication-database: admin
