server:
  port: 8040
spring:
  application:
    name: core-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/${REALM_NAME}"
  data:
    mongodb:
      username: david
      password: david
      host: localhost
      port: 27017
      database: payments
      authentication-database: admin
