server:
  port: 8040
spring:
  application:
    name: core-service
  data:
    mongodb:
      username: david
      password: david
      host: localhost
      port: 27017
      database: payments
      authentication-database: admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentRequest:com.tandapayinterview.core.kafka.PaymentRequest
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: payment:com.tandapayinterview.core.model.Payment
