server:
  port: 8090
spring:
  application:
    name: core-service
  data:
    mongodb:
      username: david
      password: david
      host: localhost
      port: 27017
      database: payment-request
      authentication-database: admin

